import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { UserProvider } from '@/context/userContext';
import AllUsersProvider from "@/context/allUsersContext";
import { SocketProvider } from "@/context/socketContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "LoopChat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <SocketProvider>
            <AllUsersProvider>
              <div className="max-w-[2160px] md:flex flex-row">
                <Navbar />
                {children}
              </div>
            </AllUsersProvider>
          </SocketProvider>
        </UserProvider>

      </body>
    </html>
  );
}
